### ISSUE TITLE
aes_gui.py error at line 81

### ISSUE THREAD

**Issue by ColinConduff** [user404d/CS6001-AES#3]
The error that I was talking about earlier occurs at line 81 in aes_gui.py

The line has: root.iconbitmap(default='aes.ico')

This occurs on mac os, python 3.5, tkinter version 8.5

Removing the "default=" portion of the argument removes the error.

So the following works for me: root.iconbitmap('aes.ico')

I'm not sure if this breaks something later on though.

**Comment by ColinConduff** [comment]
Terminal output for error:

python3 aes_gui.py 
Traceback (most recent call last):
  File "aes_gui.py", line 82, in <module>
    root.iconbitmap(default='aes.ico') # causes error on Mac OS, Tkinter version 8.5
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tkinter/__init__.py", line 1714, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, '-default', default)
_tkinter.TclError: wrong # args: should be "wm iconbitmap window ?bitmap?"

**Comment by spayne92** [comment]
This line just adds an icon image as the thumbnail for the applicatiin
window. Completely cosmetic, so it shouldn't effect anything else.

On Dec 2, 2016 11:14 AM, "Colin Conduff" <notifications@github.com> wrote:

The error that I was talking about earlier occurs at line 81 in aes_gui.py

The line has: root.iconbitmap(default='aes.ico')

This occurs on mac os, python 3.5, tkinter version 8.5

Removing the "default=" portion of the argument removes the error.

So the following works for me: root.iconbitmap('aes.ico')

I'm not sure if this breaks something later on though.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/user404d/CS6001-AES/issues/3>, or mute the thread
